// Defines the package for model classes
package com.banking.model;

// Imports BigDecimal for handling money amounts
import java.math.BigDecimal;
// Imports Timestamp to record the exact time of the transaction
import java.sql.Timestamp;

// Class representing a financial transaction (deposit or withdrawal)
public class Transaction {
    // Unique identifier for the transaction
    private int transactionId;
    // The account number associated with this transaction
    private int accountNumber;
    // The type of transaction (e.g., "DEPOSIT", "WITHDRAW")
    private String type;
    // The amount of money involved in the transaction
    private BigDecimal amount;
    // The date and time when the transaction occurred
    private Timestamp timestamp;

    // Default constructor
    public Transaction() {
    }

    // Constructor with all fields (used when retrieving history from DB)
    public Transaction(int transactionId, int accountNumber, String type, BigDecimal amount, Timestamp timestamp) {
        this.transactionId = transactionId;
        this.accountNumber = accountNumber;
        this.type = type;
        this.amount = amount;
        this.timestamp = timestamp;
    }

    // Constructor for creating a new Transaction to be saved
    // Note: transactionId and timestamp are typically generated by the DB
    public Transaction(int accountNumber, String type, BigDecimal amount) {
        this.accountNumber = accountNumber;
        this.type = type;
        this.amount = amount;
    }

    // Getter for transaction ID
    public int getTransactionId() {
        return transactionId;
    }

    // Setter for transaction ID
    public void setTransactionId(int transactionId) {
        this.transactionId = transactionId;
    }

    // Getter for account number
    public int getAccountNumber() {
        return accountNumber;
    }

    // Setter for account number
    public void setAccountNumber(int accountNumber) {
        this.accountNumber = accountNumber;
    }

    // Getter for transaction type
    public String getType() {
        return type;
    }

    // Setter for transaction type
    public void setType(String type) {
        this.type = type;
    }

    // Getter for transaction amount
    public BigDecimal getAmount() {
        return amount;
    }

    // Setter for transaction amount
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    // Getter for timestamp
    public Timestamp getTimestamp() {
        return timestamp;
    }

    // Setter for timestamp
    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    // Overrides toString to provide a readable string format of the transaction
    @Override
    public String toString() {
        return "Transaction{" +
                "transactionId=" + transactionId +
                ", accountNumber=" + accountNumber +
                ", type='" + type + '\'' +
                ", amount=" + amount +
                ", timestamp=" + timestamp +
                '}';
    }
}
